version: '3.9'

name: integrador

services:
  api:
    image: 'api:0.0.1'
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # host:container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    networks:
      - backend
      - frontend

  db:
    platform: linux/x86_64
    command: ["--max_connections=1000"]
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  web:
    image: 'web:0.0.1'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # host:container
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
    driver: bridge
    name: backend
  frontend:
    driver: bridge
    name: frontend